BIOPLIB=$HOME/git/bioplib/src

cp $BIOPLIB/angle.h             bioplib
cp $BIOPLIB/array.h             bioplib
cp $BIOPLIB/deprecated.h        bioplib
cp $BIOPLIB/fit.h               bioplib
cp $BIOPLIB/fsscanf.h           bioplib
cp $BIOPLIB/general.h           bioplib
cp $BIOPLIB/hash.h              bioplib
cp $BIOPLIB/hbond.h             bioplib
cp $BIOPLIB/macros.h            bioplib
cp $BIOPLIB/MathType.h          bioplib
cp $BIOPLIB/MathUtil.h          bioplib
cp $BIOPLIB/matrix.h            bioplib
cp $BIOPLIB/parse.h             bioplib
cp $BIOPLIB/pdb.h               bioplib
cp $BIOPLIB/port.h              bioplib
cp $BIOPLIB/seq.h               bioplib
cp $BIOPLIB/SysDefs.h           bioplib

cp $BIOPLIB/angle.c             bioplib
cp $BIOPLIB/ApMatPDB.c          bioplib
cp $BIOPLIB/array2.c            bioplib
cp $BIOPLIB/BuildConect.c       bioplib
cp $BIOPLIB/CalcRMSPDB.c        bioplib
cp $BIOPLIB/chindex.c           bioplib
cp $BIOPLIB/CopyPDB.c           bioplib
cp $BIOPLIB/DupePDB.c           bioplib
cp $BIOPLIB/fgetsany.c          bioplib
cp $BIOPLIB/FindAtomInRes.c     bioplib
cp $BIOPLIB/FindNextResidue.c   bioplib
cp $BIOPLIB/FindResidue.c       bioplib
cp $BIOPLIB/FindResidueSpec.c   bioplib
cp $BIOPLIB/fit.c               bioplib
cp $BIOPLIB/FitCaPDB.c          bioplib
cp $BIOPLIB/FitPDB.c            bioplib
cp $BIOPLIB/FNam2PDB.c          bioplib
cp $BIOPLIB/FreeStringList.c    bioplib
cp $BIOPLIB/fsscanf.c           bioplib
cp $BIOPLIB/GetCGPDB.c          bioplib
cp $BIOPLIB/GetFilestem.c       bioplib
cp $BIOPLIB/GetPDBChainLabels.c bioplib
cp $BIOPLIB/GetPDBCoor.c        bioplib
cp $BIOPLIB/GetWord.c           bioplib
cp $BIOPLIB/hash.c              bioplib
cp $BIOPLIB/hbond.c             bioplib
cp $BIOPLIB/IndexPDB.c          bioplib
cp $BIOPLIB/InStringList.c      bioplib
cp $BIOPLIB/KillLeadSpaces.c    bioplib
cp $BIOPLIB/MatMult3_33.c       bioplib
cp $BIOPLIB/OpenStdFiles.c      bioplib
cp $BIOPLIB/OriginPDB.c         bioplib
cp $BIOPLIB/padterm.c           bioplib
cp $BIOPLIB/parse.c             bioplib
cp $BIOPLIB/ParseRes.c          bioplib
cp $BIOPLIB/PDB2Seq.c           bioplib
cp $BIOPLIB/phi.c               bioplib
cp $BIOPLIB/prime.c             bioplib
cp $BIOPLIB/ReadPDB.c           bioplib
cp $BIOPLIB/SelAtPDB.c          bioplib
cp $BIOPLIB/SetExtn.c           bioplib
cp $BIOPLIB/StoreString.c       bioplib
cp $BIOPLIB/StringToUpper.c     bioplib
cp $BIOPLIB/stringutil.c        bioplib
cp $BIOPLIB/TermPDB.c           bioplib
cp $BIOPLIB/throne.c            bioplib
cp $BIOPLIB/TranslatePDB.c      bioplib
cp $BIOPLIB/upstrncmp.c         bioplib
cp $BIOPLIB/VecDist.c           bioplib
cp $BIOPLIB/WritePDB.c          bioplib
